import type { ItemDef, SpellDef } from '../types';

export const ITEMS: ItemDef[] = [
  { id: 'iron_dagger', name: 'Iron Dagger', kind: 'weapon', weight: 2, value: 15, damage: 6, skill: 'shortblade' },
  { id: 'iron_longsword', name: 'Iron Longsword', kind: 'weapon', weight: 12, value: 40, damage: 12, skill: 'longblade' },
  { id: 'iron_mace', name: 'Iron Mace', kind: 'weapon', weight: 12, value: 35, damage: 11, skill: 'blunt' },
  { id: 'chitin_spear', name: 'Chitin Spear', kind: 'weapon', weight: 10, value: 30, damage: 11, skill: 'spear' },
  { id: 'iron_axe', name: 'Iron Axe', kind: 'weapon', weight: 14, value: 38, damage: 13, skill: 'axe' },
  { id: 'short_bow', name: 'Short Bow', kind: 'weapon', weight: 4, value: 30, damage: 8, skill: 'marksman' },
  { id: 'bound_longsword', name: 'Bound Longsword', kind: 'weapon', weight: 0, value: 0, damage: 18, skill: 'longblade' },
  { id: 'sunder', name: 'Sunder', kind: 'weapon', weight: 40, value: 40000, damage: 28, skill: 'blunt' },
  { id: 'keening', name: 'Keening', kind: 'weapon', weight: 8, value: 40000, damage: 22, skill: 'shortblade' },
  { id: 'mehrunes_razor', name: "Mehrunes' Razor", kind: 'weapon', weight: 3, value: 12000, damage: 16, skill: 'shortblade' },
  { id: 'mace_of_molag_bal', name: 'Mace of Molag Bal', kind: 'weapon', weight: 22, value: 14000, damage: 20, skill: 'blunt' },
  { id: 'goldbrand', name: 'Goldbrand', kind: 'weapon', weight: 18, value: 18000, damage: 24, skill: 'longblade' },
  { id: 'spear_of_bitter_mercy', name: 'Spear of Bitter Mercy', kind: 'weapon', weight: 14, value: 12000, damage: 20, skill: 'spear' },
  { id: 'umbra_sword', name: 'Umbra', kind: 'weapon', weight: 25, value: 8000, damage: 26, skill: 'longblade' },
  { id: 'chitin_cuirass', name: 'Chitin Cuirass', kind: 'armor', weight: 12, value: 50, armor: 12, slot: 'body', skill: 'lightarmor' },
  { id: 'iron_cuirass', name: 'Iron Cuirass', kind: 'armor', weight: 24, value: 90, armor: 18, slot: 'body', skill: 'heavyarmor' },
  { id: 'netch_cuirass', name: 'Netch Leather Cuirass', kind: 'armor', weight: 10, value: 60, armor: 14, slot: 'body', skill: 'mediumarmor' },
  { id: 'steel_cuirass', name: 'Steel Cuirass', kind: 'armor', weight: 26, value: 140, armor: 22, slot: 'body', skill: 'heavyarmor' },
  { id: 'imperial_cuirass', name: 'Imperial Chain Cuirass', kind: 'armor', weight: 16, value: 120, armor: 16, slot: 'body', skill: 'mediumarmor' },
  { id: 'helm_oreyn', name: 'Helm of Oreyn Bearclaw', kind: 'armor', weight: 8, value: 9000, armor: 20, slot: 'head', skill: 'mediumarmor' },
  { id: 'wraithguard', name: 'Wraithguard', kind: 'armor', weight: 15, value: 50000, armor: 80, slot: 'gauntlet', skill: 'heavyarmor' },
  { id: 'boots_blinding_speed', name: 'Boots of Blinding Speed', kind: 'armor', weight: 4, value: 500, armor: 6, slot: 'feet', skill: 'lightarmor' },
  { id: 'common_robe', name: 'Common Robe', kind: 'clothing', weight: 2, value: 8, slot: 'body' },
  { id: 'common_shirt', name: 'Common Shirt', kind: 'clothing', weight: 1, value: 4, slot: 'body' },
  { id: 'ceremonial_robe', name: 'Ceremonial Telvanni Robe', kind: 'clothing', weight: 2, value: 200, slot: 'body' },
  { id: 'package_for_caius', name: 'Package for Caius Cosades', kind: 'quest', weight: 0.5, value: 0 },
  { id: 'directions_to_caius', name: 'Directions to Caius Cosades', kind: 'book', weight: 0.2, value: 0 },
  { id: 'dwemer_puzzle_box', name: 'Dwemer Puzzle Box', kind: 'quest', weight: 4, value: 200 },
  { id: 'antabolis_notes', name: "Hasphat's Notes", kind: 'book', weight: 0.5, value: 0 },
  { id: 'skull_llevule', name: 'Skull of Llevule Andrano', kind: 'quest', weight: 3, value: 0 },
  { id: 'muzgob_notes', name: "Sharn's Notes", kind: 'book', weight: 0.5, value: 0 },
  { id: 'zainsubani_notes', name: "Zainsubani's Notes", kind: 'book', weight: 0.5, value: 0 },
  { id: 'lost_prophecies', name: 'The Lost Prophecies', kind: 'book', weight: 1, value: 0 },
  { id: 'moon_and_star', name: 'Moon-and-Star', kind: 'armor', weight: 0.2, value: 10000, armor: 4, slot: 'ring', skill: 'unarmored' },
  { id: 'kagrenacs_notes', name: "Kagrenac's Notes", kind: 'book', weight: 0.5, value: 0 },
  { id: 'corprus_sample', name: 'Corprus Weepings', kind: 'quest', weight: 0.4, value: 0 },
  { id: 'hortator_belt', name: 'Belt of the Hortator', kind: 'clothing', weight: 1, value: 500, slot: 'belt' },
  { id: 'azuras_star', name: "Azura's Star", kind: 'soul', weight: 1, value: 5000 },
  { id: 'soul_gem', name: 'Common Soul Gem', kind: 'soul', weight: 0.5, value: 40 },
  { id: 'grand_soul_gem', name: 'Grand Soul Gem', kind: 'soul', weight: 1, value: 400 },
  { id: 'muck', name: 'Muck', kind: 'ingredient', weight: 0.1, value: 1, effects: [{ id: 'restore_fatigue', name: 'Restore Fatigue' }, { id: 'cure_disease', name: 'Cure Disease' }] },
  { id: 'marshmerrow', name: 'Marshmerrow', kind: 'ingredient', weight: 0.1, value: 1, effects: [{ id: 'restore_health', name: 'Restore Health' }, { id: 'drain_fatigue', name: 'Drain Fatigue' }] },
  { id: 'wickwheat', name: 'Wickwheat', kind: 'ingredient', weight: 0.1, value: 1, effects: [{ id: 'restore_health', name: 'Restore Health' }, { id: 'restore_fatigue', name: 'Restore Fatigue' }] },
  { id: 'saltrice', name: 'Saltrice', kind: 'ingredient', weight: 0.1, value: 1, effects: [{ id: 'restore_fatigue', name: 'Restore Fatigue' }, { id: 'restore_health', name: 'Restore Health' }] },
  { id: 'corkbulb', name: 'Corkbulb Root', kind: 'ingredient', weight: 0.1, value: 2, effects: [{ id: 'restore_health', name: 'Restore Health' }, { id: 'cure_blight', name: 'Cure Blight' }] },
  { id: 'ash_yam', name: 'Ash Yam', kind: 'ingredient', weight: 0.2, value: 1, effects: [{ id: 'restore_fatigue', name: 'Restore Fatigue' }, { id: 'fortify_attack', name: 'Fortify Attack' }] },
  { id: 'scrib_jelly', name: 'Scrib Jelly', kind: 'ingredient', weight: 0.1, value: 2, effects: [{ id: 'restore_fatigue', name: 'Restore Fatigue' }, { id: 'cure_disease', name: 'Cure Disease' }] },
  { id: 'rat_meat', name: 'Rat Meat', kind: 'ingredient', weight: 0.5, value: 1, effects: [{ id: 'restore_fatigue', name: 'Restore Fatigue' }, { id: 'damage_health', name: 'Damage Health' }] },
  { id: 'netch_leather', name: 'Netch Leather', kind: 'ingredient', weight: 1, value: 2, effects: [{ id: 'restore_fatigue', name: 'Restore Fatigue' }, { id: 'resist_fire', name: 'Resist Fire' }] },
  { id: 'willow_anther', name: 'Willow Anther', kind: 'ingredient', weight: 0.1, value: 2, effects: [{ id: 'resist_fire', name: 'Resist Fire' }, { id: 'drain_fatigue', name: 'Drain Fatigue' }] },
  { id: 'dreugh_wax', name: 'Dreugh Wax', kind: 'ingredient', weight: 0.2, value: 10, effects: [{ id: 'restore_fatigue', name: 'Restore Fatigue' }, { id: 'fortify_attack', name: 'Fortify Attack' }] },
  { id: 'fire_petal', name: 'Fire Petal', kind: 'ingredient', weight: 0.1, value: 2, effects: [{ id: 'resist_fire', name: 'Resist Fire' }, { id: 'damage_health', name: 'Damage Health' }] },
  { id: 'healing_potion', name: 'Healing Potion', kind: 'potion', weight: 0.3, value: 25, effect: { id: 'restore_health', name: 'Restore Health', magnitude: 25 } },
  { id: 'cure_disease_potion', name: 'Cure Disease Potion', kind: 'potion', weight: 0.3, value: 40, effect: { id: 'cure_disease', name: 'Cure Disease', magnitude: 1 } },
  { id: 'cure_blight_potion', name: 'Cure Blight Potion', kind: 'potion', weight: 0.3, value: 80, effect: { id: 'cure_blight', name: 'Cure Blight', magnitude: 1 } },
  { id: 'rising_force', name: 'Rising Force Potion', kind: 'potion', weight: 0.3, value: 30, effect: { id: 'restore_fatigue', name: 'Restore Fatigue', magnitude: 40 } },
  { id: 'sujamma', name: 'Sujamma', kind: 'potion', weight: 0.5, value: 15, effect: { id: 'fortify_attack', name: 'Fortify Attack', magnitude: 10 } },
  { id: 'flin', name: 'Flin', kind: 'potion', weight: 0.5, value: 12, effect: { id: 'restore_fatigue', name: 'Restore Fatigue', magnitude: 20 } },
  { id: 'moon_sugar', name: 'Moon Sugar', kind: 'misc', weight: 0.1, value: 50 },
  { id: 'lockpick', name: 'Lockpick', kind: 'misc', weight: 0.1, value: 5 },
  { id: 'probe', name: 'Probe', kind: 'misc', weight: 0.1, value: 5 },
  { id: 'silver_longsword', name: 'Silver Longsword', kind: 'weapon', weight: 12, value: 160, damage: 14, skill: 'longblade' },
  { id: 'sanguine_relic', name: 'Sanguine Relic', kind: 'quest', weight: 0.4, value: 40 },
  { id: 'guide_vvardenfell', name: 'Guide to Vvardenfell', kind: 'book', weight: 1, value: 20 },
  { id: 'journeyman_alembic', name: "Journeyman's Alembic", kind: 'misc', weight: 4, value: 80 },
  { id: 'fargoth_ring', name: "Fargoth's Ring", kind: 'quest', weight: 0.1, value: 20 },
  { id: 'rusty_dagger', name: 'Rusty Dagger', kind: 'quest', weight: 1, value: 1 },
  { id: 'sheogorath_signet', name: "Sheogorath's Signet", kind: 'quest', weight: 0.2, value: 0 },
  { id: 'raw_ebony', name: 'Raw Ebony', kind: 'misc', weight: 10, value: 200 },
  { id: 'raw_glass', name: 'Raw Glass', kind: 'misc', weight: 6, value: 150 },
  { id: 'dwemer_tube', name: 'Dwemer Tube', kind: 'quest', weight: 5, value: 100 },
  { id: 'vintage_brandy', name: 'Vintage Brandy', kind: 'quest', weight: 1, value: 100 },
  { id: 'limeware', name: 'Limeware Bowl', kind: 'quest', weight: 1, value: 40 },
  { id: 'pants', name: 'Expensive Pants', kind: 'clothing', weight: 1, value: 30, slot: 'legs' },
  { id: 'ash_statue', name: 'Ash Statue', kind: 'quest', weight: 4, value: 0 },
];

export const SPELLS: SpellDef[] = [
  { id: 'fire_bite', name: 'Fire Bite', school: 'destruction', cost: 6, effect: { id: 'fire_damage', name: 'Fire Damage', magnitude: 12 } },
  { id: 'spark', name: 'Spark', school: 'destruction', cost: 5, effect: { id: 'damage_health', name: 'Shock Damage', magnitude: 10 } },
  { id: 'heal_minor', name: 'Hearth Heal', school: 'restoration', cost: 8, effect: { id: 'restore_health', name: 'Restore Health', magnitude: 18 } },
  { id: 'restore_vigor', name: 'Second Wind', school: 'restoration', cost: 6, effect: { id: 'restore_fatigue', name: 'Restore Fatigue', magnitude: 25 } },
  { id: 'cure_common', name: 'Cure Common Disease', school: 'restoration', cost: 14, effect: { id: 'cure_disease', name: 'Cure Disease', magnitude: 1 } },
  { id: 'cure_blight_spell', name: 'Cure Blight', school: 'restoration', cost: 22, effect: { id: 'cure_blight', name: 'Cure Blight', magnitude: 1 } },
  { id: 'shield_spell', name: 'Ash Shield', school: 'alteration', cost: 10, effect: { id: 'shield', name: 'Shield', magnitude: 10 } },
  { id: 'sanctuary_spell', name: 'Blur', school: 'illusion', cost: 12, effect: { id: 'sanctuary', name: 'Sanctuary', magnitude: 10 } },
  { id: 'bound_blade', name: 'Bound Longsword', school: 'conjuration', cost: 14, effect: { id: 'bound_weapon', name: 'Bound Weapon', magnitude: 1 } },
  { id: 'detect_spell', name: 'Candle of Knowing', school: 'mysticism', cost: 8, effect: { id: 'night_eye', name: 'Detect', magnitude: 1 } },
  { id: 'mark_spell', name: 'Mark', school: 'mysticism', cost: 12, effect: { id: 'mark', name: 'Mark', magnitude: 1 } },
  { id: 'recall_spell', name: 'Recall', school: 'mysticism', cost: 12, effect: { id: 'recall', name: 'Recall', magnitude: 1 } },
  { id: 'divine_spell', name: 'Divine Intervention', school: 'mysticism', cost: 16, effect: { id: 'divine', name: 'Divine Intervention', magnitude: 1 } },
  { id: 'almsivi_spell', name: 'Almsivi Intervention', school: 'mysticism', cost: 16, effect: { id: 'almsivi', name: 'Almsivi Intervention', magnitude: 1 } },
  { id: 'resist_flame', name: 'Resist Fire', school: 'alteration', cost: 8, effect: { id: 'resist_fire', name: 'Resist Fire', magnitude: 20 } },
  { id: 'ancestor_guardian', name: 'Ancestor Guardian', school: 'conjuration', cost: 10, effect: { id: 'sanctuary', name: 'Sanctuary', magnitude: 15 } },
  { id: 'argonian_breath', name: 'Water Breathing', school: 'alteration', cost: 5, effect: { id: 'water_breathing', name: 'Water Breathing', magnitude: 1 } },
  { id: 'breton_shield', name: 'Dragon Skin', school: 'alteration', cost: 12, effect: { id: 'shield', name: 'Shield', magnitude: 20 } },
  { id: 'voice_emperor', name: 'Voice of the Emperor', school: 'illusion', cost: 8, effect: { id: 'charm', name: 'Charm', magnitude: 20 } },
  { id: 'eye_of_night', name: 'Eye of Night', school: 'illusion', cost: 5, effect: { id: 'night_eye', name: 'Night Eye', magnitude: 1 } },
  { id: 'nordic_frost', name: 'Nordic Frost', school: 'destruction', cost: 8, effect: { id: 'damage_health', name: 'Frost Damage', magnitude: 14 } },
  { id: 'berserk', name: 'Berserk', school: 'restoration', cost: 6, effect: { id: 'fortify_attack', name: 'Fortify Attack', magnitude: 20 } },
  { id: 'adrenaline', name: 'Adrenaline Rush', school: 'restoration', cost: 6, effect: { id: 'fortify_attack', name: 'Fortify Attack', magnitude: 15 } },
  { id: 'beast_tongue', name: 'Beast Tongue', school: 'illusion', cost: 6, effect: { id: 'charm', name: 'Charm', magnitude: 10 } },
  { id: 'lord_heal', name: 'Blood of the Lord', school: 'restoration', cost: 8, effect: { id: 'restore_health', name: 'Restore Health', magnitude: 30 } },
  { id: 'lover_agility', name: 'Moonlit Step', school: 'restoration', cost: 6, effect: { id: 'restore_fatigue', name: 'Restore Fatigue', magnitude: 40 } },
  { id: 'ritual_heal', name: 'Ritual Mercy', school: 'restoration', cost: 10, effect: { id: 'restore_health', name: 'Restore Health', magnitude: 40 } },
  { id: 'ritual_turn', name: 'Turn the Restless', school: 'conjuration', cost: 10, effect: { id: 'turn_undead', name: 'Turn Undead', magnitude: 1 } },
  { id: 'serpent_bite', name: 'Serpent Kiss', school: 'destruction', cost: 10, effect: { id: 'damage_health', name: 'Poison', magnitude: 18 } },
  { id: 'shadow_hide', name: 'Shadow Step', school: 'illusion', cost: 12, effect: { id: 'invisibility', name: 'Invisibility', magnitude: 1 } },
  { id: 'thief_sanctuary', name: 'Thief\'s Luck', school: 'illusion', cost: 8, effect: { id: 'sanctuary', name: 'Sanctuary', magnitude: 15 } },
  { id: 'tower_open', name: 'Tower Key', school: 'alteration', cost: 10, effect: { id: 'open', name: 'Open', magnitude: 50 } },
];

export function itemMap(): Map<string, ItemDef> {
  return new Map(ITEMS.map((i) => [i.id, i]));
}

export function spellMap(): Map<string, SpellDef> {
  return new Map(SPELLS.map((s) => [s.id, s]));
}
